### ISSUE TITLE
i want to use it but documentation is old confusing and might be compatible with the latest maxmind csv files

### ISSUE THREAD

**Issue by elnoxgdl** [ConsulTent/geoip2redis#2]
title

**Comment by azilber** [comment]
Yes, it should still be compatible with the latest maxmind csv.

**Comment by elnoxgdl** [comment]
Tried it and still getting that the file doesn't exit, even when passing the full path of the file "line 151" to be precise

**Comment by elnoxgdl** [comment]
had to compile it but it works now, thanks,.
