### ISSUE TITLE
Flag to include more fields from a CSV?

### ISSUE THREAD

**Issue by elnoxgdl** [ConsulTent/geoip2redis#3]
I was able to load the maxmind csv file into redis but when I query Redis it is storing very few information about the IP.

I would be nice to have a flag where you can specify what other columns/fields you need to load into the db.

**Comment by vodkadrunkinski** [comment]
That would be the format field.  You can tell it which of the formats
you're using and it will include more fields.

**Comment by azilber** [comment]
@elnoxgdl you can mess around with input precision to change the amount of data that gets loaded.  You've provided scarcely any information.   GeoiP2Redis defaults to the first version of the CSV format (DB1).  It technically supports all the formats using input precision:  https://github.com/ConsulTent/geoip2redis/wiki/Usage

So the flags do exist, please read the wiki.
